name: Dependabot Tasks

# This workflow makes use of labels to selectively run jobs. However, when a PR is opened and triggers
# this workflow, the labels are not yet available. This means that we need to run this workflow twice
# with different jobs "enabled".
# If we add a dependency to the labeler, we would have to handle the label event separately, so we
# add instead the labeled/unlabeled types to the pull_request event.

# A dependency to the labeler workflow is necessary, but at the time the labels are needed,
# the labeler should have finished its job.

# IMPORTANT NOTE: If not enough action runners are available, and the labeler workflow is scheduled
# after this workflow, tests will be skipped.
# If we add a workflow dependency to the labeler, we would have to handle the label event separately.

on:
  pull_request:
    branches:
      - 'main'
      - 'branch_*'

  # Execute on push so that when dependabot pushes changes, it will properly re-trigger the workflow.
  push:
    branches:
      - 'main'
      - 'branch_*'

jobs:
  # Dependabot job that runs only for dependabot PRs
  # This job is writing locks, updates checksums, and commits the changes on the dependabot PRs.
  # Once changes are committed and pushed, it will re-trigger the workflow on the latest commit and skip this job.
  lock-and-verify:
    name: Lock and verify

    runs-on: self-hosted

    # Run only on PRs created by dependabot, this prevents users from misusing branch names
    # prefixed with dependabot/**
    # This job is not executed at the end of this job with the push, as the commit is done by github-actions.
    # Otherwise, a condition should be added to trigger this only once.
    if: github.actor == 'dependabot[bot]'

    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}

    # Give the default GITHUB_TOKEN write permission to commit
    # and push the changed files back to the repository.
    permissions:
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          java-package: jdk

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Use Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-precommit-${{ hashFiles('versions.lock') }}
          restore-keys: |
            ${{ runner.os }}-gradle-precommit-
            ${{ runner.os }}-gradle-

      - name: Write locks
        run: ./gradlew writeLocks

      - name: Update licenses / checksums
        run: ./gradlew updateLicenses

      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Write locks and update checksums"
          git push origin ${{ github.head_ref }}
